### ISSUE TITLE
moveTo theta only behaves strangely

### ISSUE THREAD

**Issue by Pandhariix** [ProtolabSBRE/qibullet#10]
moveTo theta only behaves strangely (see gif below). The code used is the following:
```python
pepper.moveTo(0, 0, 1.5, _async=True)
time.sleep(0.5)
pepper.moveTo(0, 0, 1.5, _async=True)
time.sleep(0.5)
pepper.moveTo(0, 0, 1.5, _async=True)
time.sleep(0.5)
```
![Peek 2019-04-26 17-49](https://user-images.githubusercontent.com/11226450/56820246-ab763f00-684b-11e9-9b6f-7fdb0bbd0093.gif)

**Comment by mcaniot** [comment]
It's came from` pybullet.getQuaternionFromEuler(...)` that convert with a modulo between [0, pi]
